/** Musteri gorselleri - duzenli listeler */

export const heroSliderImages = [
  "/musteri/hero/s01.webp",
  "/musteri/hero/s02.webp",
  "/musteri/hero/s03.webp",
  "/musteri/hero/s04.webp",
  "/musteri/hero/s05.webp",
  "/musteri/hero/s06.webp",
  "/musteri/hero/s07.webp",
  "/musteri/hero/s08.webp",
  "/musteri/hero/s09.webp",
  "/musteri/hero/s10.webp",
  "/musteri/hero/s11.webp",
  "/musteri/hero/s12.webp",
];

export const dusakabinUst = [
  "/musteri/dusakabin/ust/01.webp",
  "/musteri/dusakabin/ust/02.webp",
  "/musteri/dusakabin/ust/03.webp",
  "/musteri/dusakabin/ust/04.webp",
  "/musteri/dusakabin/ust/05.webp",
  "/musteri/dusakabin/ust/06.webp",
  "/musteri/dusakabin/ust/07.webp",
  "/musteri/dusakabin/ust/08.webp",
  "/musteri/dusakabin/ust/09.webp",
  "/musteri/dusakabin/ust/10.webp",
  "/musteri/dusakabin/ust/11.webp",
  "/musteri/dusakabin/ust/12.webp",
  "/musteri/dusakabin/ust/13.webp",
  "/musteri/dusakabin/ust/14.webp",
  "/musteri/dusakabin/ust/15.webp",
  "/musteri/dusakabin/ust/16.webp",
  "/musteri/dusakabin/ust/17.webp",
  "/musteri/dusakabin/ust/18.webp",
  "/musteri/dusakabin/ust/19.webp",
  "/musteri/dusakabin/ust/20.webp",
  "/musteri/dusakabin/ust/21.webp",
  "/musteri/dusakabin/ust/22.webp",
  "/musteri/dusakabin/ust/23.webp",
  "/musteri/dusakabin/ust/24.webp",
  "/musteri/dusakabin/ust/25.webp",
  "/musteri/dusakabin/ust/26.webp",
  "/musteri/dusakabin/ust/27.webp",
  "/musteri/dusakabin/ust/28.webp",
  "/musteri/dusakabin/ust/29.webp",
  "/musteri/dusakabin/ust/30.webp",
  "/musteri/dusakabin/ust/31.webp",
  "/musteri/dusakabin/ust/32.webp",
  "/musteri/dusakabin/ust/33.webp",
  "/musteri/dusakabin/ust/34.webp",
  "/musteri/dusakabin/ust/35.webp",
  "/musteri/dusakabin/ust/36.webp",
];

export const dusakabinAlt = [
  "/musteri/dusakabin/alt/01.webp",
  "/musteri/dusakabin/alt/02.webp",
  "/musteri/dusakabin/alt/03.webp",
  "/musteri/dusakabin/alt/04.webp",
  "/musteri/dusakabin/alt/05.webp",
  "/musteri/dusakabin/alt/06.webp",
  "/musteri/dusakabin/alt/07.webp",
  "/musteri/dusakabin/alt/08.webp",
  "/musteri/dusakabin/alt/09.webp",
  "/musteri/dusakabin/alt/10.webp",
  "/musteri/dusakabin/alt/11.webp",
  "/musteri/dusakabin/alt/12.webp",
  "/musteri/dusakabin/alt/13.webp",
  "/musteri/dusakabin/alt/14.webp",
  "/musteri/dusakabin/alt/15.webp",
  "/musteri/dusakabin/alt/16.webp",
  "/musteri/dusakabin/alt/17.webp",
  "/musteri/dusakabin/alt/18.webp",
  "/musteri/dusakabin/alt/19.webp",
  "/musteri/dusakabin/alt/20.webp",
  "/musteri/dusakabin/alt/21.webp",
  "/musteri/dusakabin/alt/22.webp",
  "/musteri/dusakabin/alt/23.webp",
  "/musteri/dusakabin/alt/24.webp",
  "/musteri/dusakabin/alt/25.webp",
  "/musteri/dusakabin/alt/26.webp",
  "/musteri/dusakabin/alt/27.webp",
];

export const tesisatUst = [
  "/musteri/tesisat/ust/01.webp",
  "/musteri/tesisat/ust/02.webp",
  "/musteri/tesisat/ust/03.webp",
  "/musteri/tesisat/ust/04.webp",
  "/musteri/tesisat/ust/05.webp",
  "/musteri/tesisat/ust/06.webp",
  "/musteri/tesisat/ust/07.webp",
];

export const tesisatAlt = [
  "/musteri/tesisat/alt/01.webp",
  "/musteri/tesisat/alt/02.webp",
  "/musteri/tesisat/alt/03.webp",
  "/musteri/tesisat/alt/04.webp",
  "/musteri/tesisat/alt/05.webp",
  "/musteri/tesisat/alt/06.webp",
  "/musteri/tesisat/alt/07.webp",
  "/musteri/tesisat/alt/08.webp",
  "/musteri/tesisat/alt/09.webp",
  "/musteri/tesisat/alt/10.webp",
  "/musteri/tesisat/alt/11.webp",
  "/musteri/tesisat/alt/12.webp",
];

export const klozetUst = [
  "/musteri/klozet/ust/01.webp",
  "/musteri/klozet/ust/02.webp",
  "/musteri/klozet/ust/03.webp",
  "/musteri/klozet/ust/04.webp",
  "/musteri/klozet/ust/05.webp",
  "/musteri/klozet/ust/06.webp",
  "/musteri/klozet/ust/07.webp",
  "/musteri/klozet/ust/08.webp",
  "/musteri/klozet/ust/09.webp",
  "/musteri/klozet/ust/10.webp",
  "/musteri/klozet/ust/11.webp",
  "/musteri/klozet/ust/12.webp",
  "/musteri/klozet/ust/13.webp",
  "/musteri/klozet/ust/14.webp",
  "/musteri/klozet/ust/15.webp",
  "/musteri/klozet/ust/16.webp",
  "/musteri/klozet/ust/17.webp",
  "/musteri/klozet/ust/18.webp",
  "/musteri/klozet/ust/19.webp",
  "/musteri/klozet/ust/20.webp",
  "/musteri/klozet/ust/21.webp",
  "/musteri/klozet/ust/22.webp",
  "/musteri/klozet/ust/23.webp",
  "/musteri/klozet/ust/24.webp",
  "/musteri/klozet/ust/25.webp",
  "/musteri/klozet/ust/26.webp",
];

export const klozetAlt = [
  "/musteri/klozet/alt/01.webp",
  "/musteri/klozet/alt/02.webp",
  "/musteri/klozet/alt/03.webp",
  "/musteri/klozet/alt/04.webp",
  "/musteri/klozet/alt/05.webp",
  "/musteri/klozet/alt/06.webp",
  "/musteri/klozet/alt/07.webp",
  "/musteri/klozet/alt/08.webp",
  "/musteri/klozet/alt/09.webp",
  "/musteri/klozet/alt/10.webp",
  "/musteri/klozet/alt/11.webp",
  "/musteri/klozet/alt/12.webp",
  "/musteri/klozet/alt/13.webp",
  "/musteri/klozet/alt/14.webp",
  "/musteri/klozet/alt/15.webp",
  "/musteri/klozet/alt/16.webp",
  "/musteri/klozet/alt/17.webp",
];

export const muslukUst = [
  "/musteri/musluk/ust/01.webp",
  "/musteri/musluk/ust/02.webp",
  "/musteri/musluk/ust/03.webp",
  "/musteri/musluk/ust/04.webp",
  "/musteri/musluk/ust/05.webp",
  "/musteri/musluk/ust/06.webp",
  "/musteri/musluk/ust/07.webp",
  "/musteri/musluk/ust/08.webp",
  "/musteri/musluk/ust/09.webp",
];

export const muslukAlt = [
  "/musteri/musluk/alt/01.webp",
  "/musteri/musluk/alt/02.webp",
  "/musteri/musluk/alt/03.webp",
  "/musteri/musluk/alt/04.webp",
  "/musteri/musluk/alt/05.webp",
  "/musteri/musluk/alt/06.webp",
  "/musteri/musluk/alt/07.webp",
  "/musteri/musluk/alt/08.webp",
  "/musteri/musluk/alt/09.webp",
];

export const fayansUst = [
  "/musteri/fayans/ust/01.webp",
  "/musteri/fayans/ust/02.webp",
  "/musteri/fayans/ust/03.webp",
  "/musteri/fayans/ust/04.webp",
  "/musteri/fayans/ust/05.webp",
  "/musteri/fayans/ust/06.webp",
  "/musteri/fayans/ust/07.webp",
  "/musteri/fayans/ust/08.webp",
];

export const fayansAlt = [
  "/musteri/fayans/alt/01.webp",
  "/musteri/fayans/alt/02.webp",
  "/musteri/fayans/alt/03.webp",
  "/musteri/fayans/alt/04.webp",
  "/musteri/fayans/alt/05.webp",
  "/musteri/fayans/alt/06.webp",
  "/musteri/fayans/alt/07.webp",
];

export const mutfakUst = [
  "/musteri/mutfak/ust/01.webp",
  "/musteri/mutfak/ust/02.webp",
  "/musteri/mutfak/ust/03.webp",
  "/musteri/mutfak/ust/04.webp",
];

export const mutfakAlt = [
  "/musteri/mutfak/alt/01.webp",
  "/musteri/mutfak/alt/02.webp",
  "/musteri/mutfak/alt/03.webp",
  "/musteri/mutfak/alt/04.webp",
  "/musteri/mutfak/alt/05.webp",
  "/musteri/mutfak/alt/06.webp",
  "/musteri/mutfak/alt/07.webp",
];

